first version
RT-Thread-packages/ota_downloader pull request #1
Opened 2019-02-20 07:34 UTC by balanceTWK

2019-02-20 07:46 UTC, SummerGift requested changes

2019-02-20 07:46 UTC, SummerGGift commented on README.md
> +## 3、使用 OTA Downloader
完善 readme

2019-02-20 07:46 UTC, SummerGGift commented on SConscript
> +Return('group')
末尾添加空行

2019-02-20 10:14 UTC, SummerGift approved these changes

2019-02-20 10:32 UTC, armink requested changes

2019-02-20 10:32 UTC, armink commented on README.md
> +        [*]  OTA Downloader : Various firmware downloaders on rt-thread  --->
- 更新配置，讲解配置
- The firmware downloader which using on RT-Thread OTA component.

2019-02-20 10:32 UTC, armink commented on README.md
> +OTA Downloader package 遵循 LGPLv2.1 许可，详见 `LICENSE` 文件。
Apache

2019-02-20 10:32 UTC, armink commented on README.md
> +烧录程序到目标开发板，用户可在 FinSH 终端找到两个命令：`http_ota` 和 `ymodema_ota`。
ymodem

2019-02-20 10:32 UTC, armink commented on README.md
> +OTA Downloader 是与 OTA 服务器对应的客户端程序，用于将 OTA 固件从 OTA 服务器下载到设备。常用的且通用的 OTA Downloader 有 Y-modem（串口升级） 和 HTTP OTA（网络升级），开发者使用自己的电脑既可搭建用于 OTA 升级的服务端。私有云或者公有云平台提供的 OTA 服务器，通常需要开发对应的客户端程序，运行在设备端，用于下载 OTA 固件。
完善介绍

2019-02-20 10:32 UTC, armink commented on README.md
> +![ymodem_ota](picture/ymodem_ota.png)
docs/figures

2019-02-20 10:32 UTC, armink commented on README.md
> +> 更多详细信息可参考 《RT-Thread OTA 用户手册》: docs/UM1004-RT-Thread-OTA 用户手册.pdf
文档可以独立章节

2019-02-20 10:32 UTC, armink commented on README.md
> +> 更多详细信息可参考 《RT-Thread OTA 用户手册》: docs/UM1004-RT-Thread-OTA 用户手册.pdf
完善注意事项

2019-02-20 10:32 UTC, armink commented on http_ota.c
> +#include <stdio.h>
宏包裹文件

2019-02-20 10:32 UTC, armink commented on SConscript
> +if GetDepend(['PKG_USING_YMODEA_OTA']):
全局搜一下 YMODEM

2019-02-20 10:32 UTC, armink commented on http_ota.c
> +#ifdef HTTP_OTA_DEBUG
更换 OTA_DOWNLOADER_DEBUG

2019-02-20 10:32 UTC, armink commented on ymodem_ota.c
> +    rt_kprintf("Waring: Ymodem has started! This operator will not recovery.\n");
Warning

2019-02-20 10:32 UTC, armink commented on ymodem_ota.c
> +MSH_CMD_EXPORT(ymodem_ota, OTA by ymodem);
完善描述

2019-02-21 03:09 UTC, armink commented on README.md
> +| 命令 | 功能 |
删除，使用无序

2019-02-21 03:09 UTC, armink commented on README.md
> +- http 下载方式依赖于 webclient 软件包
http/https

2019-02-21 03:09 UTC, armink commented on README.md
> +            [*]  Enable YMODEA OTA
YMODEA

2019-02-21 03:44 UTC, SummerGift requested changes

2019-02-21 03:44 UTC, SummerGift commented on README.md
> +OTA Downloader 是由 RT-Thread 团队推出的，用于 ota 固件升级的软件包，该软件包提供多种协议方式下载固件，如常用的协议： `Y-modem（串口升级）` ， `HTTP OTA（网络升级）` 等。开发者可以根据自己的需求在软件包管理器中灵活选择自己想要的升级方式，且软件包提供的每种升级方式都只需一个命令就可实现固件升级。下表是目前软件包支持的命令：
OTA Downloader 改为中文，如 OTA 固件下载器

2019-02-21 03:44 UTC, SummerGGift commented on README.md
> +本软件包是用于 OTA 升级的固件下载器，该下载器提供多种固件下载方式。开发者可以根据自己的需求灵活选择升级方式，每种升级方式都只需调用一次相应的函数或者执行一次相应的命令就可实现。下面是目前支持的方式。
每种升级方式都只需调用一次相应的函数或者执行一次相应的命令就可实现 > 每种升级方式都只需调用一次函数或命令即可实现，下面是目前支持的下载方式：

2019-02-21 03:44 UTC, SummerGGift commented on README.md
> +- YMODEM 下载方式依赖于 ymodem 组件
YMODEM 下载方式依赖于 ymodem 组件 统一格式   
fal 需要大写

2019-02-21 06:06 UTC, merged