【修改】： ymodem_ota -p factory 指定接收分区名参数
RT-Thread-packages/ota_downloader pull request #2
Opened 2019-03-27 10:45 UTC by SummerGGift

2019-03-27 12:03 UTC, SummerGGift commented
@armink

2019-03-28 01:30 UTC, armink requested changes

2019-03-28 01:30 UTC, armink commented on src/ymodem_ota.c
> +                rt_kprintf("Usage: ymodem_ota -p <partitonname>.\n");
partition name

2019-03-28 01:30 UTC, armink commented on src/ymodem_ota.c
> +static char* recv_partition = "download";
#define DEFAULT_DOWNLOAD_PART "download"

2019-03-28 01:30 UTC, armink commented on src/ymodem_ota.c
> +static char* recv_partition = "download";
这里定义为变量无法实现默认功能

2019-03-28 02:31 UTC, merged